### ISSUE TITLE
template.json 格式问题

### ISSUE THREAD

**Issue by 88250** [sublimeclemency/reflection#1]
你好，有个小问题需要修改一下：

![image](https://github.com/sublimeclemency/reflection/assets/873584/c25ca873-ff80-43d7-ae53-6cbc179ac075)

请参考 https://github.com/siyuan-note/template-sample 项目，这里是个数组：

![image](https://github.com/sublimeclemency/reflection/assets/873584/9607d4fb-df44-4676-8fd5-a81c07309ab3)

**Comment by sublimeclemency** [comment]
fixed!

**Comment by 88250** [comment]
记得发布新版本，谢谢。

**Comment by 88250** [comment]
你好，目前还是有问题，请升级版本号并 release 新版本：

```
E 2024/01/24 11:10:30 template.go:59: get community template [sublimeclemency/reflection@4044bc510f7c64d656dcf2a6126afa4f7de0f050] failed: json: cannot unmarshal string into Go struct field Funding.funding.custom of type []string
```
